using Microsoft.Azure.ServiceBus;
using Microsoft.Azure.ServiceBus.Core;
using Moosesoft.Azure.ServiceBus.FailurePolicy;
using System.Threading.Tasks;

namespace Moosesoft.Azure.ServiceBus
{
    /// <summary>
    /// Azure Service Bus plugin designed to handle deferred messages generated by the <see cref="DeferMessageFailurePolicy"/>.
    /// </summary>
    public class DeferredMessagePlugin : ServiceBusPlugin
    {
        private readonly IMessageReceiver _messageReceiver;

        /// <inheritdoc />
        public override string Name => nameof(DeferredMessagePlugin);

        /// <summary>
        /// Initialize a new instance <see cref="DeferredMessagePlugin"/>.
        /// </summary>
        /// <param name="messageReceiver"></param>
        public DeferredMessagePlugin(IMessageReceiver messageReceiver)
        {
            _messageReceiver = messageReceiver;
        }

        /// <inheritdoc />
        public override Task<Message> AfterMessageReceive(Message message)
        {
            return _messageReceiver.GetDeferredMessageAsync(message);
        }
    }
}